In [1]:
import numpy as np

## **Rotation Matrix to X-Y-Z Fixed Angle**

In [2]:
def Rotational_matrix_to_XYZ_fixed_angle(Rxyz):
    r11, r12, r13 = Rxyz[0]
    r21, r22, r23 = Rxyz[1]
    r31, r32, r33 = Rxyz[2]

    beta = np.degrees(np.arctan2(-r31, (np.sqrt(r11**2 + r21**2))))
    alpha = np.degrees(np.arctan2(r21/np.cos(beta), r11/np.cos(beta)))
    gama = np.degrees(np.arctan2(r32/np.cos(beta), r33/np.cos(beta)))

    alpha, beta, gama = np.round([alpha, beta, gama], 0)

    return np.array([alpha,beta,gama])

## **X-Y-Z Fixed Angle to Rotation Matrix**

In [3]:
def XYZ_fixed_angle_to_Rotational_matrix(XYZ_fixed_angle):
    alpha, beta, gama = XYZ_fixed_angle

    cos_alpha = np.cos(np.deg2rad(alpha))
    cos_beta = np.cos(np.deg2rad(beta))
    cos_gama = np.cos(np.deg2rad(gama))
    sin_alpha = np.sin(np.deg2rad(alpha))
    sin_beta = np.sin(np.deg2rad(beta))
    sin_gama = np.sin(np.deg2rad(gama))

    r11 = cos_alpha*cos_beta
    r12 = (cos_alpha*sin_beta*sin_gama) - (sin_alpha*cos_gama)
    r13 = (cos_alpha*sin_beta*cos_gama) + (sin_alpha*sin_gama)
    r21 = sin_alpha*cos_beta
    r22 = (sin_alpha*sin_beta*sin_gama) + (cos_alpha*cos_gama)
    r23 = (sin_alpha*sin_beta*cos_gama) - (cos_alpha*sin_gama)
    r31 = -1*sin_beta
    r32 = cos_beta*sin_gama
    r33 = cos_beta*cos_gama

    Rxyz = np.array([
        [round(r11,3), round(r12,3), round(r13,3)],
        [round(r21,3), round(r22, 3), round(r23,3)],
        [round(r31,3), round(r32,3), round(r33,3)],
    ])

    return Rxyz


### **Test1**

In [4]:
rotation_matrix = XYZ_fixed_angle_to_Rotational_matrix([30,50,90])
rotation_matrix

array([[ 0.557,  0.663,  0.5  ],
       [ 0.321,  0.383, -0.866],
       [-0.766,  0.643,  0.   ]])

In [6]:
xyz_fixed_angle = Rotational_matrix_to_XYZ_fixed_angle(rotation_matrix)
xyz_fixed_angle

array([30., 50., 90.])

## **Rotation Matrix to Z-Y-Z Euler Angle**

In [7]:
def Rotational_matrix_to_ZYZ_euler_angle(Rzyz):
    r11, r12, r13 = Rzyz[0]
    r21, r22, r23 = Rzyz[1]
    r31, r32, r33 = Rzyz[2]
   

    beta = [np.degrees(np.arctan2(np.sqrt(r13**2+r23**2),r33)), np.degrees(-1*np.arctan2(np.sqrt(r13**2+r23**2),r33))]
    alpha = np.degrees(np.arctan2( (r23/np.sin(np.deg2rad(beta))), (r13/np.sin(np.deg2rad(beta)))))
    gama = np.degrees(np.arctan2((r32/np.sin(np.deg2rad(beta))), -1*(r31/np.sin(np.deg2rad(beta)))))

    alpha, beta, gama = np.round([alpha, beta, gama], 0)
    return np.array([alpha, beta, gama])
    

### **Z-Y-Z Euler Angle to Rotation Matrix**

In [8]:
def ZYZ_euler_angle_to_Rotational_matrix(ZYZ_fixed_angle):
    alpha, beta, gama = ZYZ_fixed_angle

    cos_alpha = np.cos(np.deg2rad(alpha))
    cos_beta = np.cos(np.deg2rad(beta))
    cos_gama = np.cos(np.deg2rad(gama))
    sin_alpha = np.sin(np.deg2rad(alpha))
    sin_beta = np.sin(np.deg2rad(beta))
    sin_gama = np.sin(np.deg2rad(gama))

    r11 = (cos_alpha*cos_beta*cos_gama) - (sin_alpha*sin_gama)
    r12 = (-1*sin_alpha*cos_gama) - (cos_alpha*cos_beta*sin_gama)
    r13 = cos_alpha*sin_beta
    r21 = (sin_alpha*cos_beta*cos_gama) + (cos_alpha*sin_gama)
    r22 = (cos_alpha*cos_gama) - (sin_alpha*cos_beta*sin_gama)
    r23 = sin_alpha*sin_beta
    r31 = sin_beta*cos_gama
    r32 = -1*sin_beta*sin_gama
    r33 = cos_beta

    Rzyz = np.array([
        [round(r11,3), round(r12,3), round(r13,3)],
        [round(r21,3), round(r22, 3), round(r23,3)],
        [round(r31,3), round(r32,3), round(r33,3)],
    ])

    return Rzyz

### **Test2**

In [9]:
rotation_matrix = ZYZ_euler_angle_to_Rotational_matrix([30,50,90])
rotation_matrix

array([[-0.5  , -0.557,  0.663],
       [ 0.866, -0.321,  0.383],
       [ 0.   , -0.766,  0.643]])

In [10]:
zyz_euler_angle = Rotational_matrix_to_ZYZ_euler_angle(rotation_matrix)
zyz_euler_angle

array([[  30., -150.],
       [  50.,  -50.],
       [ -90.,   90.]])

## **Rotaton Matrix to Eulers Parameter**

In [11]:
def Rotaton_Matrix_to_Eulers_Parameter(Re):
    r11, r12, r13 = Re[0]
    r21, r22, r23 = Re[1]
    r31, r32, r33 = Re[2]

    e1, e2, e3, e4 = None, None, None, None 

    e4 = 0.5 * np.sqrt(1 + r11 + r22 + r33)
    if e4 != 0:
        e1 = (r32 - r23) / (4 * e4)
        e2 = (r13 - r31) / (4 * e4)
        e3 = (r21 - r12) / (4 * e4)

    return e1, e2, e3, e4

## **Eulers Parameter Rotaton Matrix**

In [12]:
def Eulers_Parameter_Rotaton_Matrix(e1, e2, e3, e4):
    r11 = 1 - (2 * e2**2) - (2 * e3**2)
    r12 = 2 * ((e1 * e2) - (e3 * e4))
    r13 = 2 * ((e1 * e3) + (e2 * e4)) 
    r21 = 2 * ((e1 * e2) + (e3 * e4))
    r22 = 1 - (2 * e1**2) - (2 * e3**2)
    r23 = 2 * ((e2 * e3) - (e1 * e4))
    r31 = 2 * ((e1 * e3) - (e2 * e4))
    r32 = 2 * ((e2 * e3) + (e1 * e4))
    r33 = 1 - (2 * e1**2) - (2 * e2**2)

    Re = np.array([
        [r11, r12, r13],
        [r21, r22, r23],
        [r31, r32, r33]
    ])

    return Re

### **Test3**

In [13]:
rotation_matrix = Eulers_Parameter_Rotaton_Matrix(0.0, 0.0, 0.0, 1.0)
rotation_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
euler_parameters = Rotaton_Matrix_to_Eulers_Parameter(rotation_matrix)
euler_parameters

(0.0, 0.0, 0.0, 1.0)